#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate fields/<slug>.md pages from _data/fields.yml (single source of truth).
# Usage: ruby scripts/generate_fields.rb

require "yaml"
require "pathname"
require "fileutils"
require "date"

ROOT = Pathname.new(__dir__).parent
FIELDS = ROOT.join("_data/fields.yml")
OUT = ROOT.join("fields")

fields = YAML.safe_load(File.read(FIELDS), permitted_classes: [Date, Time], aliases: true) || []
FileUtils.mkdir_p(OUT)

generated = []
fields.each do |field|
  slug = field["slug"].to_s
  name = field["name"].to_s
  raise "Field missing slug" if slug.empty?

  path = OUT.join("#{slug}.md")
  content = <<~MD
    ---
    layout: field
    field: #{slug}
    title: #{name}
    permalink: /fields/#{slug}/
    # Generated by scripts/generate_fields.rb — edit _data/fields.yml, then re-run.
    ---
  MD
  File.write(path, content)
  generated << slug
  puts "wrote fields/#{slug}.md"
end

# Remove stale field pages that are no longer in fields.yml
Dir.glob(OUT.join("*.md").to_s).each do |path|
  slug = File.basename(path, ".md")
  next if generated.include?(slug)
  File.delete(path)
  puts "removed stale fields/#{slug}.md"
end

puts "Done — #{generated.size} field page(s)."
